INSERT INTO Plays (play_id, play_title) VALUES (1, 'Hamlet');
INSERT INTO Plays (play_id, play_title) VALUES (2, 'Macbeth');
INSERT INTO Plays (play_id, play_title) VALUES (3, 'Romeo and Juliet');

INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', '[stage direction]', 'FRANCISCO at his post. Enter to him BERNARDO', NULL);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Bernardo', 'Who''s there?', 1);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Francisco', 'Nay, answer me: stand, and unfold yourself.', 2);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Bernardo', 'Long live the king!', 3);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Francisco', 'Bernardo?', 4);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Bernardo', 'He.', 5);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Francisco', 'You come most carefully upon your hour.', 6);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Bernardo', '''Tis now struck twelve; get thee to bed, Francisco.', 7);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Francisco', 'For this relief much thanks: ''tis bitter cold,', 8);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Francisco', 'And I am sick at heart.', 9);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Bernardo', 'Have you had quiet guard?', 10);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Francisco', 'Not a mouse stirring.', 11);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Bernardo', 'Well, good night.', 12);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Bernardo', 'If you do meet Horatio and Marcellus,', 13);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Bernardo', 'The rivals of my watch, bid them make haste.', 14);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Francisco', 'I think I hear them. Stand, ho! Who''s there?', 15);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', '[stage direction]', 'Enter HORATIO and MARCELLUS', NULL);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Horatio', 'Friends to this ground.', 16);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Marcellus', 'And liegemen to the Dane.', 17);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Francisco', 'Give you good night.', 18);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Marcellus', 'O, farewell, honest soldier:', 19);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Marcellus', 'Who hath relieved you?', 20);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Francisco', 'Bernardo has my place.', 21);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', 'Francisco', 'Give you good night.', 22);
INSERT INTO hamlet (play_id, act, scene, character_name, dialogue, line_number) VALUES (1, 'Act I', 'Scene I', '[stage direction]', 'Exit', NULL);

INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene I', '[stage direction]', 'Thunder and lightning. Enter three Witches', NULL);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene I', 'First Witch', 'When shall we three meet again', 1);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene I', 'First Witch', 'In thunder, lightning, or in rain?', 2);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene I', 'Second Witch', 'When the hurlyburly''s done,', 3);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene I', 'Second Witch', 'When the battle''s lost and won.', 4);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene I', 'Third Witch', 'That will be ere the set of sun.', 5);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene I', 'First Witch', 'Where the place?', 6);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene I', 'Second Witch', 'Upon the heath.', 7);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene I', 'Third Witch', 'There to meet with Macbeth.', 8);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene I', 'First Witch', 'I come, Graymalkin!', 9);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene I', 'Second Witch', 'Paddock calls.', 10);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene I', 'Third Witch', 'Anon.', 11);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene I', 'All', 'Fair is foul, and foul is fair:', 12);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene I', 'All', 'Hover through the fog and filthy air.', 13);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene I', '[stage direction]', 'Exeunt', NULL);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene II', '[stage direction]', 'Alarum within. Enter DUNCAN, MALCOLM, DONALBAIN, LENNOX, with Attendants, meeting a bleeding Sergeant', NULL);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene II', 'Duncan', 'What bloody man is that? He can report,', 14);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene II', 'Duncan', 'As seemeth by his plight, of the revolt', 15);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene II', 'Duncan', 'The newest state.', 16);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene II', 'Malcolm', 'This is the sergeant', 17);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene II', 'Malcolm', 'Who like a good and hardy soldier fought', 18);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene II', 'Malcolm', '''Gainst my captivity. Hail, brave friend!', 19);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene II', 'Malcolm', 'Say to the king the knowledge of the broil', 20);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene II', 'Malcolm', 'As thou didst leave it.', 21);
INSERT INTO macbeth (play_id, act, scene, character_name, dialogue, line_number) VALUES (2, 'Act I', 'Scene II', 'Sergeant', 'Doubtful it stood;', 22);

INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Prologue', 'Chorus', 'Two households, both alike in dignity,', 1);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Prologue', 'Chorus', 'In fair Verona, where we lay our scene,', 2);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Prologue', 'Chorus', 'From ancient grudge break to new mutiny,', 3);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Prologue', 'Chorus', 'Where civil blood makes civil hands unclean.', 4);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Prologue', 'Chorus', 'From forth the fatal loins of these two foes', 5);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Prologue', 'Chorus', 'A pair of star-cross''d lovers take their life;', 6);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Prologue', 'Chorus', 'Whose misadventured piteous overthrows', 7);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Prologue', 'Chorus', 'Do with their death bury their parents'' strife.', 8);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Prologue', 'Chorus', 'The fearful passage of their death-mark''d love,', 9);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Prologue', 'Chorus', 'And the continuance of their parents'' rage,', 10);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Prologue', 'Chorus', 'Which, but their children''s end, nought could remove,', 11);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Prologue', 'Chorus', 'Is now the two hours'' traffic of our stage;', 12);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Prologue', 'Chorus', 'The which if you with patient ears attend,', 13);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Prologue', 'Chorus', 'What here shall miss, our toil shall strive to mend.', 14);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Scene I', '[stage direction]', 'Enter SAMPSON and GREGORY, of the house of Capulet, armed with swords and bucklers', NULL);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Scene I', 'Sampson', 'Gregory, o'' my word, we''ll not carry coals.', 15);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Scene I', 'Gregory', 'No, for then we should be colliers.', 16);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Scene I', 'Sampson', 'I mean, an we be in choler, we''ll draw.', 17);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Scene I', 'Gregory', 'Ay, while you live, draw your neck out o'' the collar.', 18);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Scene I', 'Sampson', 'I strike quickly, being moved.', 19);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Scene I', 'Gregory', 'But thou art not quickly moved to strike.', 20);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Scene I', 'Sampson', 'A dog of the house of Montague moves me.', 21);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Scene I', 'Gregory', 'To move is to stir; and to be valiant is to stand:', 22);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Scene I', 'Gregory', 'therefore, if thou art moved, thou runn''st away.', 23);
INSERT INTO romeo_juliet (play_id, act, scene, character_name, dialogue, line_number) VALUES (3, 'Act I', 'Scene I', 'Sampson', 'A dog of that house shall move me to stand: I will', 24);